#!/bin/bash

API_URL="https://pokeapi.co/api/v2/pokemon/Pikachu"

OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

# Make the API request
response=$(curl -s -S -f -w "%{http_code}" "$API_URL" -o "$OUTPUT_FILE")

# Check the HTTP status code
if ["$response" -ne 200 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - Request failed with status code: $response" >> "$ERROR_FILE"
    echo "Error logged to $ERROR_FILE"
else
    echo "Data saved to $OUTPUT_FILE"
fi
