#!/bin/bash

# Variables
POKEMON_LIST=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon") # Pokémon list
API_URL="https://pokeapi.co/api/v2/pokemon/"
ERROR_FILE="errors.txt"

DELAY_SECONDS=2 # Delay between requests to avoid rate limiting


# Log errors to errors.txt
log_error() {
    # $1: the message passed to the function
    local error_message="$1"
    # prepend with timestamp and append the error message to the error log file
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] - ERROR: $error_message" >> "$ERROR_FILE"
}
fetch_data() {
    local POKEMON_NAME="$1"
    local API_URL="${API_URL}${POKEMON_NAME}"
    local OUTPUT_FILE="${POKEMON_NAME}.json"

    echo "Trying to fetch data for ${POKEMON_NAME}..."

    local status_code
    local response 
    response=$(curl -s -S -f -w "%{http_code}" "$API_URL" 2>/dev/null)
    status_code="${response: -3}" # Last 3 characters (the status code)
    response="${response%???}"  # All the response except the last 3 characters

    # Check the HTTP status code
if ["$status_code" -eq 200 ]; then
    echo "$response" > "$OUTPUT_FILE"
    echo "Data saved to ${OUTPUT_FILE}"
    return 0
else
    local error_message="Failed to fetch data. HTTP Status Code: ${response}. URL: ${API_URL}"
    log_error "${error_message}"
    return 1
fi

}

for name in "${POKEMON_LIST[@]}"; do
    fetch_data "$name"
    if [[ "$name" != "${POKEMON_LIST[-1]}" ]]; then
        sleep "$DELAY_SECONDS"
    fi
done

echo "Batch retrieval complete."